apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c2r5d73va-python
  janus-idp.io/tekton: c2r5d73va-python
  backstage.io/kubernetes-id: c2r5d73va-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: c2r5d73va-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
